### ISSUE TITLE
Runs this regularly on a server?

### ISSUE THREAD

**Issue by freenerd** [guardian/gu-who#35]
Hey,

great tool you built here, thanks for opening it up.

I was wondering: when do the checks run? Is it regularly via some internal scheduling, triggered by a cron or only when a user logs in? From reading code I think it's the later only, correct? How do you run this at the Guardian?

My ideal case here would be to run this on a server (with an access token of a user who's in the bots group).

**Comment by robbiet480** [comment]
Seems the webhook is now broken. Just tried deploying gu-who on Heroku and got this error:

`Caused by: java.lang.IllegalArgumentException: requirement failed`
