### ISSUE TITLE
mention the grace period in the issues that are open

### ISSUE THREAD

**Issue by afeld** [guardian/gu-who#47]
When the policy violation issues are opened, it might be nice to let the user know how long they have to fix the issue(s). That being said, I understand that giving a specific amount of time will cause people to procrastinate. Maybe something in the middle, like "you have a limited amount of time to fix these issues". Thoughts?

/cc @jgrevich

**Comment by rtyley** [comment]
I've opened a pull request in #49 based off your suggestion, let me know what you think! Out of interest, what GitHub org are you using _gu:who_ with?

**Comment by afeld** [comment]
Nice, thanks! We're in the final stages of testing it out for @18F.
