### ISSUE TITLE
warning confuses when issue closed in same comment

### ISSUE THREAD

**Issue by dx-pbuckley** [guardian/gu-who#54]
Hi, I'm running gu-who on my org and on my second run (initial run 30 days ago, next run today) noticed that it comments with a "scary" sounding warning and closes the issue in the same comment. It seems confusing that it would warn "you're going to be removed on 11 Dec" and "you're good to go" in the same comment. Is this something that you would welcome a fix for (I could try my hand at putting in a PR for it)?

```
WARNING: If requirements for this account aren't met, it will be removed from DataXu, Inc.'s organisation on Friday, December 11, 2015.

Thanks for fixing those requirements (ie Sponsor). Closing this issue, you're good to go! :sparkles:
```
<img width="684" alt="screen shot 2015-12-08 at 4 02 56 pm" src="https://cloud.githubusercontent.com/assets/8352591/11668518/a2bf6818-9dc5-11e5-818f-dec26811e442.png">

**Comment by rtyley** [comment]
Thanks for this bug report @dx-pbuckley - yep, the `userShouldReceiveFinalWarning` value is being set to true when it shouldn't, as you can see here:

https://github.com/guardian/gu-who/blob/a30bcfc6f/app/views/ghIssues/memberUserUpdate.scala.html#L4-L10
